## 1. 加载库

> 在数据处理中pandas往往是主角，而numpy负责提供底层数值支持，让计算变得更简单快捷。因此在这里，我们同时导入这两个库

In [1]:
import pandas as pd
import numpy as np

## 2. 创建 DataFrame

> pandas 的核心是 **DataFrame**（表格）和 **Series**（一列）。它们可以存储数据，并对这些数据进行方便快捷的操作计算  
>DataFrame的创建有很多方法，从字典创建最为直观：key 是列名，value 是列数据。

In [2]:
# 用字典创建一个小 DataFrame
df = pd.DataFrame({
    'name':    ['Alice', 'Bob',   'Charlie', 'David', 'Eve'],
    'age':     [25,      30,      35,        28,      30],
    'salary':  [5000,    6000,    7000,      5500,    6000],
    'dept':    ['IT',    'HR',    'IT',      'HR',    'IT']
})
df

      name  age  salary dept
0    Alice   25    5000   IT
1      Bob   30    6000   HR
2  Charlie   35    7000   IT
3    David   28    5500   HR
4      Eve   30    6000   IT

In [3]:
# Series：DataFrame 的一列
print(df['name'])       # 取出 name 列
print(type(df['name']))

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
Name: name, dtype: object
<class 'pandas.core.series.Series'>

## 3. 读写数据

> 工作中用 `pd.read_csv('文件路径.csv')` 读文件、`.to_csv()` 存文件。

In [4]:
# 读取 CSV 文件（这里我们以'dataset/students.csv'做演示）
df_from_file = pd.read_csv('dataset/students.csv')
df_from_file

# 保存为 CSV（用 Excel 就能打开）
df_from_file.to_csv('输出.csv', index=False)

## 4. 查看数据

> 拿到表格后先**扫一眼**：长什么样、什么类型、数据分布。

In [5]:
df.head()     # 前 5 行

      name  age  salary dept
0    Alice   25    5000   IT
1      Bob   30    6000   HR
2  Charlie   35    7000   IT
3    David   28    5500   HR
4      Eve   30    6000   IT

In [6]:
df.info()     # 列数、非空数、数据类型

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   age     5 non-null      int64
 2   salary  5 non-null      int64
 3   dept    5 non-null      object
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [7]:
df.describe() # 数值列的统计摘要（count / mean / std / min / max）

             age       salary
count   5.000000     5.000000
mean   29.600000  5900.000000
std     3.646917   741.619849
min    25.000000  5000.000000
25%    28.000000  5500.000000
50%    30.000000  6000.000000
75%    30.000000  6000.000000
max    35.000000  7000.000000

In [8]:
print('形状:', df.shape)             # (行, 列)
print('列名:', df.columns.tolist())
print('类型:\n', df.dtypes)         # 每列类型

形状: (5, 4)
列名: ['name', 'age', 'salary', 'dept']
类型:
 name      object
age        int64
salary     int64
dept      object
dtype: object

## 5. 计算统计量

> 对数值列算均值、中位数等，快速了解数据的集中趋势和离散程度。

In [9]:
print('平均工资:', df['salary'].mean())
print('工资中位数:', df['salary'].median())
print('标准差:',   df['salary'].std())
print('最低工资:',  df['salary'].min())
print('最高工资:',  df['salary'].max())

平均工资: 5900.0
工资中位数: 6000.0
标准差: 741.6198487095663
最低工资: 5000
最高工资: 7000

## 6. 索引与筛选

> 记住这四种取数方式就够了。

In [10]:
# loc：按列名取
df.loc[0:2, ['name', 'salary']]

      name  salary
0    Alice    5000
1      Bob    6000
2  Charlie    7000

In [11]:
# iloc：按位置取
df.iloc[0:3, 0:2]

      name  age
0    Alice   25
1      Bob   30
2  Charlie   35

In [12]:
# 布尔索引：按条件筛选
df[df['salary'] > 5500]

      name  age  salary dept
1      Bob   30    6000   HR
2  Charlie   35    7000   IT
4      Eve   30    6000   IT

In [13]:
# query：用字符串写条件，更直观
df.query("dept == 'IT' & salary > 5500")

      name  age  salary dept
2  Charlie   35    7000   IT
4      Eve   30    6000   IT

## 7. 缺失值

> 三步走：**检测 -> 填充 -> 删除**。

In [14]:
# 创建一个带缺失值的 DataFrame
df_miss = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, np.nan, 5],
    'C': [1, 2, 3, 4, 5]
})
print('原始数据:')
print(df_miss)

原始数据:
     A    B  C
0  1.0  NaN  1
1  2.0  2.0  2
2  NaN  3.0  3
3  4.0  NaN  4
4  5.0  5.0  5

In [15]:
# 检测
print('逐列缺失数:')
print(df_miss.isnull().sum())

逐列缺失数:
A    1
B    2
C    0
dtype: int64

In [16]:
# 填充
df_filled = df_miss.copy()
df_filled['A'] = df_filled['A'].fillna(df_filled['A'].mean())  # 用均值
df_filled['B'] = df_filled['B'].fillna(0)                       # 用固定值，如0
print('填充后:')
print(df_filled)

填充后:
     A    B  C
0  1.0  0.0  1
1  2.0  2.0  2
2  3.0  3.0  3
3  4.0  0.0  4
4  5.0  5.0  5

In [17]:
# 删除含 NaN 的行
print('删除含 NaN 的行:')
print(df_miss.dropna())

删除含 NaN 的行:
     A    B  C
1  2.0  2.0  2
4  5.0  5.0  5

## 8. 分组聚合

> `groupby` 先按某列的值把数据拆成若干组，再对每组算统计值。
>
> 比如我们按 `dept`（部门）分组，数据会被拆成两组：
> - **IT 组** → Alice、Charlie、Eve（3 人）
> - **HR 组** → Bob、David（2 人）
>
> 拆完后就能算"IT 平均工资多少？HR 平均工资多少？"——这就是聚合。

In [18]:
print('各部门平均工资:')
print(df.groupby('dept')['salary'].mean())
print()
print('各部门人数:')
print(df['dept'].value_counts())

各部门平均工资:
dept
HR    5750.0
IT    6000.0
Name: salary, dtype: float64

各部门人数:
dept
IT    3
HR    2
Name: count, dtype: int64

In [19]:
# 一次算多个统计量
df.groupby('dept')['salary'].agg(['mean', 'max', 'min', 'count'])

        mean   max   min  count
dept
HR    5750.0  6000  5500      2
IT    6000.0  7000  5000      3

## 9. 新增列

> 基于已有列创建新列。

In [20]:
df['bonus'] = df['salary'] * 0.2          # 向量化运算
df['total'] = df['salary'] + df['bonus']
df[['name', 'salary', 'bonus', 'total']]

      name  salary   bonus   total
0    Alice    5000  1000.0  6000.0
1      Bob    6000  1200.0  7200.0
2  Charlie    7000  1400.0  8400.0
3    David    5500  1100.0  6600.0
4      Eve    6000  1200.0  7200.0

## 10. 排序

> `.sort_values('要排序的列名', ascending=True)`——默认升序（小→大）。  
> `ascending=False` 即降序（大→小）。  
> 多列排序时传列表，每列可分别指定升/降序。

In [21]:
print('按工资降序（高→低）:')
print(df.sort_values('salary', ascending=False)[['name', 'salary']])
print()
print('按工资升序（低→高，默认就是升序）:')
print(df.sort_values('salary')[['name', 'salary']])
print()
print('先按部门、再按工资降序:')
print(df.sort_values(['dept', 'salary'], ascending=[True, False]))

按工资降序（高→低）:
      name  salary
2  Charlie    7000
4      Eve    6000
1      Bob    6000
3    David    5500
0    Alice    5000

按工资升序（低→高，默认就是升序）:
      name  salary
0    Alice    5000
3    David    5500
1      Bob    6000
4      Eve    6000
2  Charlie    7000

先按部门、再按工资降序:
      name  age  salary dept   bonus   total
1      Bob   30    6000   HR  1200.0  7200.0
3    David   28    5500   HR  1100.0  6600.0
2  Charlie   35    7000   IT  1400.0  8400.0
4      Eve   30    6000   IT  1200.0  7200.0
0    Alice   25    5000   IT  1000.0  6000.0

## 11. 合并

> `concat` 纵向堆叠，`merge` 横向拼接。

In [22]:
# concat：按行堆叠
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})
print('纵向堆叠:')
print(pd.concat([df1, df2]))
print()
# merge：按 key 拼接
left  = pd.DataFrame({'id': [1, 2, 3], 'name': ['A', 'B', 'C']})
right = pd.DataFrame({'id': [1, 2, 4], 'score': [85, 92, 78]})
print('按 id 合并(inner):')
print(pd.merge(left, right, on='id', how='inner'))

纵向堆叠:
   A  B
0  1  3
1  2  4
0  5  7
1  6  8

按 id 合并(inner):
   id name  score
0   1    A     85
1   2    B     92